import { StyleSheet } from "react-native";
import { colors } from "../constants/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    paddingTop: 60,
    paddingBottom: 16,
    paddingHorizontal: 20,
  },
  headerTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
    position: "relative",
  },
  backButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    left: 0,
  },
  backIcon: {
    fontSize: 28,
    color: "#1A1A1A",
    fontFamily: "Outfit_400Regular",
  },
  headerTitle: {
    fontSize: 24,
    fontFamily: "Outfit_600SemiBold",
    color: "#1A1A1A",
  },
  headerDate: {
    fontSize: 16,
    fontFamily: "Outfit_400Regular",
    color: "#1A1A1A",
    textAlign: "center",
  },
  tabContainer: {
    flexDirection: "row",
    marginHorizontal: 60,
    marginTop: 16,
    marginBottom: 32,
    height: 40,
    alignItems: "center",
  },
  tab: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#E0E0E0",
    borderRadius: 20,
    height: 40,
  },
  tabSeparator: {
    width: 20,
    height: 3,
    backgroundColor: "#2A4163",
  },
  tabActive: {
    backgroundColor: "#2A4163",
    borderColor: "#2A4163",
  },
  tabInactive: {
    borderColor: "#2A4163",
    borderWidth: 2.5,
  },
  tabBreath: {
    borderColor: "#2A4163",
    borderWidth: 2.5,
  },
  tabText: {
    fontSize: 16,
    fontFamily: "Outfit_500Medium",
    color: "#666666",
  },
  tabTextActive: {
    color: "#FFFFFF",
  },
  tabTextBreath: {
    color: "#1A1A1A",
  },
  content: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: 140,
    paddingHorizontal: 20,
    zIndex: 10,
  },
  timerCard: {
    backgroundColor: "#DDF1F1",
    borderRadius: 32,
    paddingVertical: 36,
    paddingHorizontal: 28,
    alignItems: "center",
    width: "100%",
    maxWidth: 380,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 10,
    zIndex: 10,
  },
  timerCircleOuter: {
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: "#DDF1F1",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 28,
    shadowColor: "#000",
    shadowOffset: {
      width: -4,
      height: -4,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
  },
  circleContainer: {
    width: 240,
    height: 240,
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
  },
  svgContainer: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 240,
    height: 240,
  },
  progressDot: {
    position: "absolute",
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#FFFFFF",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
    zIndex: 10,
  },
  circleInner: {
    position: "absolute",
    top: 10,
    left: 10,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: "#DDF1F1",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    zIndex: 5,
  },
  timerContent: {
    alignItems: "center",
  },
  goalText: {
    fontSize: 14,
    fontFamily: "Outfit_400Regular",
    color: "#666666",
    marginBottom: 12,
  },
  timerDisplay: {
    fontSize: 56,
    fontFamily: "Outfit_700Bold",
    color: "#1A1A1A",
  },
  buttonSeparatorContainer: {
    position: "relative",
    alignItems: "center",
    marginVertical: 24,
    marginHorizontal: -28,
  },
  curvedSeparator: {
    position: "absolute",
    top: "50%",
    marginTop: -50,
    width: "100%",
    zIndex: 1,
  },
  startButton: {
    backgroundColor: colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 48,
    borderRadius: 28,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
    zIndex: 2,
  },
  startButtonText: {
    fontSize: 18,
    fontFamily: "Outfit_600SemiBold",
    color: "#FFFFFF",
  },
  pauseButton: {
    backgroundColor: colors.primary,
    paddingVertical: 12,
    paddingHorizontal: 48,
    borderRadius: 28,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
    zIndex: 2,
  },
  pauseButtonText: {
    fontSize: 18,
    fontFamily: "Outfit_600SemiBold",
    color: "#FFFFFF",
  },
  guidanceText: {
    fontSize: 16,
    fontFamily: "Outfit_400Regular",
    color: "#1A1A1A",
    textAlign: "center",
    lineHeight: 24,
  },
});
