import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  bottomNavContainer: {
    position: "absolute",
    bottom: 8,
    left: 20,
    right: 20,
    height: 88,
    zIndex: 1000,
    elevation: 1000,
  },
  bottomNavBackground: {
    position: "absolute",
    width: "100%",
    height: "100%",
  },
  bottomNavContent: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 24,
  },
  navItem: {
    alignItems: "center",
    justifyContent: "center",
    width: 48,
    height: 48,
    position: "relative",
    zIndex: 1001,
  },
  navItemIndicator: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#3AAFA9",
    position: "absolute",
    bottom: 0,
  },
  aiButton: {
    width: 116,
    height: 116,
    borderRadius: 58,
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    bottom: 26,
    left: "50%",
    marginLeft: -58,
    backgroundColor: "transparent",
    elevation: 1001,
    zIndex: 1001,
  },
});
