import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 24,
    paddingTop: 60,
    paddingBottom: 8,
    backgroundColor: "#FFFFFF",
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#2B5F5F",
    justifyContent: "center",
    alignItems: "center",
  },
  avatarText: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "600",
    fontFamily: "Outfit_600SemiBold",
  },
  dateText: {
    fontSize: 14,
    color: "#757575",
    fontWeight: "400",
    fontFamily: "Outfit_400Regular",
  },
  notificationButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#E0F2F1",
    justifyContent: "center",
    alignItems: "center",
  },
  greetingSection: {
    paddingHorizontal: 24,
    paddingTop: 16,
    paddingBottom: 8,
    backgroundColor: "#FFFFFF",
  },
  greetingTop: {
    fontSize: 20,
    color: "#9E9E9E",
    fontWeight: "400",
    marginBottom: 4,
    fontFamily: "Outfit_400Regular",
  },
  greetingName: {
    fontSize: 32,
    fontWeight: "700",
    color: "#1A1A1A",
    fontFamily: "Outfit_700Bold",
  },
  moodSection: {
    backgroundColor: "#1A1A1A",
    marginHorizontal: 24,
    marginTop: 16,
    borderRadius: 20,
    padding: 24,
  },
  moodQuestion: {
    fontSize: 18,
    fontWeight: "600",
    color: "#FFFFFF",
    marginBottom: 20,
    fontFamily: "Outfit_600SemiBold",
  },
  moodOptions: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  moodOption: {
    alignItems: "center",
    gap: 8,
  },
  moodEmoji: {
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "transparent",
  },
  moodEmojiSelected: {
    transform: [{ scale: 1.5 }],
  },
  moodEmojiText: {
    fontSize: 36,
  },
  moodLabel: {
    fontSize: 14,
    color: "#FFFFFF",
    fontWeight: "500",
    fontFamily: "Outfit_500Medium",
  },
  ritualCard: {
    marginHorizontal: 20,
    marginTop: 24,
    borderRadius: 20,
    position: "relative",
    overflow: "hidden",
    height: 284,
  },
  ritualCardBackground: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: "100%",
    height: "100%",
  },
  ritualCardContent: {
    flex: 1,
    padding: 24,
    zIndex: 1,
    justifyContent: "space-between",
  },
  ritualLabel: {
    fontSize: 14,
    color: "#2E7D5F",
    fontWeight: "500",
    marginBottom: 12,
    fontFamily: "Outfit_500Medium",
  },
  ritualTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: "#1A1A1A",
    marginBottom: 8,
    fontFamily: "Outfit_700Bold",
  },
  ritualSubtitle: {
    fontSize: 16,
    color: "#4A4A4A",
    fontWeight: "400",
    marginBottom: 24,
    fontFamily: "Outfit_400Regular",
  },
  ritualButtons: {
    flexDirection: "row",
    gap: 12,
  },
  startButton: {
    flex: 1,
    backgroundColor: "#3AAFA9",
    paddingVertical: 14,
    borderRadius: 25,
    alignItems: "center",
  },
  startButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    fontFamily: "Outfit_600SemiBold",
  },
  scheduleLaterButton: {
    flex: 1,
    backgroundColor: "transparent",
    paddingVertical: 14,
    borderRadius: 25,
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#3AAFA9",
  },
  scheduleLaterButtonText: {
    color: "#3AAFA9",
    fontSize: 16,
    fontWeight: "600",
    fontFamily: "Outfit_600SemiBold",
  },
  ritualDecoration: {
    position: "absolute",
    right: -20,
    top: 20,
    opacity: 0.1,
  },
  scrollContent: {
    paddingBottom: 120,
  },
  centerContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F5F5F5",
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: "#757575",
  },
  errorText: {
    fontSize: 16,
    color: "#E53935",
    marginBottom: 20,
    textAlign: "center",
  },
  retryButton: {
    backgroundColor: "#3AAFA9",
    paddingVertical: 12,
    paddingHorizontal: 30,
    borderRadius: 25,
  },
  retryButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
});
