import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 40,
    paddingTop: 100,
    paddingBottom: 60,
  },
  title: {
    fontSize: 28,
    fontFamily: "Outfit_600SemiBold",
    color: "#1A1A1A",
    marginBottom: 12,
    textAlign: "center",
  },
  subtitle: {
    fontSize: 16,
    fontFamily: "Outfit_400Regular",
    color: "#1A1A1A",
    textAlign: "center",
    marginBottom: 60,
  },
  timePickerContainer: {
    flexDirection: "row",
    borderRadius: 45,
    paddingVertical: 0,
    paddingHorizontal: 0,
    marginBottom: 80,
    gap: 0,
    height: 200,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.3)",
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    position: "relative",
  },
  pickerColumn: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "transparent",
  },
  topBorder: {
    position: "absolute",
    top: "40%",
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    pointerEvents: "none",
  },
  bottomBorder: {
    position: "absolute",
    bottom: "31.5%",
    left: 0,
    right: 0,
    height: 1,
    backgroundColor: "rgba(255, 255, 255, 0.3)",
    pointerEvents: "none",
  },
  picker: {
    width: 100,
    height: 200,
    backgroundColor: "transparent",
  },
  confirmButton: {
    width: "100%",
    marginBottom: 16,
  },
  cancelButton: {
    width: "100%",
    paddingVertical: 18,
    paddingHorizontal: 32,
    alignItems: "center",
    backgroundColor: "transparent",
    borderRadius: 30,
    borderWidth: 1.5,
    borderColor: "rgba(255, 255, 255, 0.3)",
  },
  cancelButtonText: {
    fontSize: 16,
    fontFamily: "Outfit_500Medium",
    color: "#FFFFFF",
  },
});
